- name: Update Package Cache (apt/Ubuntu)
  tags: always
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == 'Debian'
  # when: ansible_distribution == "Ubuntu"

- name: Update Package Cache (dnf/CentOS)
  tags: always
  dnf:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == 'RedHat'
  # when: ansible_distribution == "CentOS"

- name: Update Package Cache (yum/Amazon)
  tags: always
  yum:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Amazon"

- name: Install base packages
  ansible.builtin.package:
    name:
    - lvm2
    - docker.io
    - net-tools
    - python3
    - python3-pip

- name: create docker config directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755
  notify:
  - docker-restart-enable

- name: Copy daemon config for docker
  template:
    src: "docker-daemon.json.j2"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
  - docker-restart-enable

- name: Create a 2048-bit SSH key for user ceph in ~ceph/.ssh/id_rsa
  ansible.builtin.user:
    name: "{{ceph_user}}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present

- name: Add sudo nopasswd  for user "{{ceph_user}}"
  lineinfile: 
    dest: '/etc/sudoers'
    line: '{{ ceph_user }} ALL=(ALL) NOPASSWD:ALL'
    create: yes


- name: Download cephadm
  get_url:
    url: "{{cephadm_url}}"
    dest: /usr/bin/cephadm
    mode: '0555'


- name: Create local directory
  ansible.builtin.file:
    path: /tmp/ceph_nodes_pub/
    state: directory
    mode: 0777
  register: local_dir
  delegate_to: localhost


- name: ansible copy file from remote to local.
  fetch:
    src: "/home/{{ceph_user}}/.ssh/id_rsa.pub"
    # dest: "/tmp/ceph_nodes_pub/{{ansible_host}}"
    dest: "{{local_dir.path}}/pub-{{ inventory_hostname }}"
    flat: yes


- name: Set authorized key taken from file
  authorized_key:
    user: "{{ceph_user}}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
  - "{{local_dir.path}}*"


- meta: flush_handlers